php:
    build: ./dockers/php/
    volumes_from:
        - app
    container_name: cron-php

app:
    image: php:7.1
    volumes:
        - ./src:/scripts
        - ./data/logs:/var/log
    command: "true"
    container_name: cron-app